 3 To- Do- Task
 Please Complete all the problem listed below.
 3.1 Warm Up Exercises:
 1. Sorting and Subsetting:
 Complete all following Task:
 • Dataset for the Task: "titanic.csv"
 Following task is common for all the problem:
 i. Load the provided dataset and import in pandas DataFrame.
 ii. Check info of the DataFrame and identify following:
 Problem 1- Sorting:
 a. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
 head of the result.
 b. Create a DataFrame called class
 age that contains only the Pclass and Age columns of the Titanic
 dataset, in that order. Print the head of the result.
 c. Create a DataFrame called survived
 gender that contains the Survived and Sex columns of the
 Titanic dataset, in that order.Print the head of the result.

In [1]:
import pandas as pd
dataframe = pd.read_csv("/content/drive/MyDrive/AI_SEM3/Datasets/Titanic-Dataset.csv")
dataframe.head()
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [2]:
#1
fare =dataframe['Fare']
fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [3]:
#2
class_age = dataframe[['Pclass', 'Age']]
print(class_age.head())

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [4]:
#3
survived_gender = dataframe[['Survived', 'Sex']]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

 Problem- 2- Subsetting:
 Complete all the following Task:
 Subsetting Rows:

 1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
 to fare 100.View the printed result.
 class.

 2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
 first-class. View the printed result.

 3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
 is female (Sex is "female"), assigning it to female  18. View the printed result.

 Subsetting Rows by Categorical variables:
 under

 i. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
 (Southampton), assigning the result to embarked
 c
 or
 s. View the printed result.
 ii. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
 or second class), assigning the result to first
 second
 class.View the printed result.

In [5]:
#1
fare_gt_100 = dataframe[dataframe['Fare']>100][['Fare']]
fare_gt_100.head()

         Fare
27   263.0000
31   146.5208
88   263.0000
118  247.5208
195  146.5208

In [6]:
#2
first_class= dataframe[dataframe['Pclass']==1][['Pclass']]
print(first_class.head())

    Pclass
1        1
3        1
6        1
11       1
23       1

In [7]:
import pandas as pd
dataframe = pd.read_csv("/content/drive/MyDrive/AI_SEM3/Datasets/Titanic-Dataset.csv")

#3
female_18 = dataframe[(dataframe['Age']<18) & (dataframe['Sex']=='female')][['Age','Sex']]
female_18.head()

     Age     Sex
9   14.0  female
10   4.0  female
14  14.0  female
22  15.0  female
24   8.0  female

In [8]:
# Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S" (Southampton)

embarked = dataframe[(dataframe['Embarked']=='C') | (dataframe['Embarked']=='S')][['Embarked']]
embarked.head

<bound method NDFrame.head of     Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
884        S
886        S
887        S
888        S
889        C

[812 rows x 1 columns]>

In [9]:
# ii. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2]
first_second_class = dataframe[dataframe['Pclass'].isin([1, 2])][['Pclass']]
first_second_class.head()

    Pclass
1        1
3        1
6        1
9        2
11       1

 3.2 Exploratory Data Analysis Practice Exercise-1.

 Answer the following questions from Dataset:

In [10]:
# 1.Add a column to the Titanic dataset,fare_per_year, containing the fare divided by the age of the passenger(i.e.,Fare/Age).
dataframe['fare_per_year'] = dataframe['Fare']/dataframe['Age']
dataframe.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000

In [11]:
# 2. Subset rows where fare_per_year is higher than 5,assigning this to high_fare_age.
fare_per_year_higher_5 = dataframe[dataframe['fare_per_year']>5]
fare_per_year_higher_5.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

In [12]:
# 3. Sort high_fare_age by descending fare_per_year,assigning this to high_fare_age_srt.
high_fare_age_srt = fare_per_year_higher_5.sort_values(by='fare_per_year', ascending=False)
high_fare_age_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

In [13]:
# 4. Select only the Name and fare_per_year columns of high_fare_age_srt and save the result as result.

result = high_fare_age_srt[['Name', 'fare_per_year']]
result.head()

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

 Whichadultmalepassenger(age≥18andSexis’male’)paidthehighestfarerelativetotheir
 class?
 Toanswerthequestionperformfollowingoperations:
 1.AddacolumntotheTitanicdataset,fareperclass,containingthefare divided by thepassenger
 classi.e. Fare /Pclass.
 2. Subset rowswherethepassenger ismale(Sexis”male”)andanadult(Age isgreaterthanorequal
 to18),assigningthistoadultmales.
 3. Sort adultmalesbydescendingfareperclass,assigningthistoadultmalessrt.
 4. Select only the Name, Age, andfareperclasscolumnsof adultmalessrandsavetheresult
 asresult.
 5. Lookattheresult.

In [14]:
#1
import pandas as pd
dataframe = pd.read_csv("/content/drive/MyDrive/AI_SEM3/Datasets/Titanic-Dataset.csv")

# Add a new column 'fareperyear' which is Fare divided by Age
dataframe['fare_per_year'] = dataframe['Fare'] / dataframe['Age']
# Add a new column 'fareperclass' (Fare divided by Pclass)
dataframe['fareperclass'] = dataframe['Fare'] / dataframe['Pclass']
dataframe.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fareperclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333

In [15]:
#2 Subset rows for adult male passengers (Age >= 18 and Sex == "male")
adultmales = dataframe[(dataframe['Sex'] == 'male') & (dataframe['Age'] >= 18)]
adultmales.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fareperclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0.960417,51.862500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,0.402500,2.683333
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,0.801923,10.425000

In [16]:
#3 Sort adultmales by 'fareperclass' in descending order
adult_males_srt = adultmales.sort_values(by='fareperclass', ascending=False)
adult_males_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fareperclass
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14.637977,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14.231367,512.3292
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105,263.0000
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,4.109375,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,10.313367,247.5208

In [17]:
#4 Select only 'Name', 'Age', and 'fareperclass' columns
result = adult_males_srt[['Name', 'Age', 'fareperclass']]
result.head()

                                   Name   Age  fareperclass
737              Lesurer, Mr. Gustave J  35.0      512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0      512.3292
27       Fortune, Mr. Charles Alexander  19.0      263.0000
438                   Fortune, Mr. Mark  64.0      263.0000
118            Baxter, Mr. Quigg Edmond  24.0      247.5208

 3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:
 Based on the dataset Answer the following question:

 1. Calculate the total Fare paid across all passengers in the Titanic dataset.
 2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
 3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
 4. Combine the fare totals from first, second, and third classes into a list.
 5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [18]:
#1 Total Fare paid across all passengers
total_fare = dataframe['Fare'].sum()
print(f"Total Fare paid across all passengers in the Titanic dataset: {total_fare}")

Total Fare paid across all passengers in the Titanic dataset: 28693.9493

In [19]:
#2 In first class (Pclass is 1)
first_class_fare = dataframe[dataframe['Pclass'] == 1]['Fare'].sum()
print(f"Total Fare paid by passengers in first class: {first_class_fare}")

Total Fare paid by passengers in first class: 18177.4125

In [20]:
#3 In  second class (Pclass is 2) and third class (Pclass is 3)
second_class_fare = dataframe[dataframe['Pclass'] == 2]['Fare'].sum()
print(f"Total Fare paid by passengers in second class: {second_class_fare}")

third_class_fare = dataframe[dataframe['Pclass'] == 3]['Fare'].sum()
print(f"Total Fare paid by passengers in third class: {third_class_fare}")

Total Fare paid by passengers in second class: 3801.8417
Total Fare paid by passengers in third class: 6714.6951

In [21]:
#4 Combine the fare totals from first, second, and third classes into a list.
fare_totals = [first_class_fare, second_class_fare, third_class_fare]
print(f"Fare totals for each class: {fare_totals}")

Fare totals for each class: [18177.4125, 3801.8417, 6714.6951]

In [22]:
#5 The proportion of fare revenue by class
fare_proportions = [first_class_fare / total_fare, second_class_fare / total_fare, third_class_fare / total_fare]
print(f"Proportion of fare revenue by class: {fare_proportions}")

Proportion of fare revenue by class: [0.6334928771899656, 0.1324962855496507, 0.23401083726038366]